
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SheetCustom from "@/components/Custom/SheetCustom";
import SideMenuBar from "@/components/Custom/SideMenuBar";
import { Suspense } from 'react'
import AuthProvider from "@/components/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider >

          <body className={inter.className}>
            <div className="flex gap-2 w-full mt-[0.5px] ">
              <div className=" hidden sm:block  ">
                <SideMenuBar></SideMenuBar>
              </div>
              <main className="flex-1" id="mainTag">
                <Suspense fallback={<p>Loading feed...</p>}>
                  {children}
                </Suspense>
              </main>
            </div>
          </body>
      </AuthProvider>
    </html>
  );
}
